### PR TITLE
Server: Delete Unix domain socket after shutdown

### LINKED ISSUE #4673: Unable to start photoprism container if domain socket file is exist
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

If a domain socket file persists, photoprism container does not start.
The socket file usually is created and not deleted in previous container run. 

#### 2. How can we reproduce it?

1. Start photoprism container using unix domain socket in a persistent volume or bind mount.
2. Stop and restart the same container.

#### 3. What behavior do you expect?

Start normally. To do so, photoprism container should delete the socket file on exit or on start.

#### 4. What could be the cause of your problem?

The undeleted unix socket file. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

My container log:

```
started 240915 as root (amd64-prod)
init: https
Creation of a default HTTPS/TLS certificate is skipped because PHOTOPRISM_DEFAULT_TLS is "false".
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
running as uid 0
/opt/photoprism/bin/photoprism start
time="2024-12-20T07:48:48Z" level=info msg="Become a member today, support our mission and enjoy our member benefits! 💎"
time="2024-12-20T07:48:48Z" level=info msg="Visit https://www.photoprism.app/membership to learn more."
time="2024-12-20T07:48:48Z" level=info msg="server: enabled gzip compression"
time="2024-12-20T07:48:48Z" level=info msg="webdav: disabled"
time="2024-12-20T07:48:48Z" level=error msg="server: failed to listen on unix socket (listen unix /var/sock/photoprism.sock: bind: address already in use)"
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 &  `docker.io/photoprism/photoprism:latest`

(b) Database Type & Version: MariaDB & `mariadb:11`

(c) Operating System Types & Versions: Linux, Fedora 41, Podman 5.3.1 

(d) Browser Types & Versions: Not related

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Not related

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: DeskMini X300 / AMD Ryzen 7 5700G

(b) Physical Memory & Swap Space in GB: 32GB

(c) Storage Type: SSD

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

I'm using Apache as a Reverse Proxy using the domain socket.

### PR DESCRIPTION
**Pull request by omerdduran**
Fixes #4673: Unable to start photoprism container if domain socket file is exist

Added proper cleanup of Unix Domain Socket files both during server startup and shutdown to prevent "address already in use" errors and ensure clean server restarts.

### CODE REVIEW

File: internal/server/start.go [hunk 1]
```diff
@@ -181,6 +189,15 @@ func Start(ctx context.Context, conf *config.Config) {
 	if err != nil {
 		log.Errorf("server: shutdown failed (%s)", err)
 	}
+
+	// Clean up Unix Domain Socket file if it exists
+	if unixSocket := conf.HttpSocket(); unixSocket != "" {
+		if err := os.Remove(unixSocket); err != nil && !os.IsNotExist(err) {
```
Comment (alexislefebvre) [inline internal/server/start.go]: Is it possible to move this code to a function to avoid repeating it?

Comment (omerdduran) [reply internal/server/start.go]: Of course

**Comment by lastzero** [comment]
It looks like the socket is also deleted when the server starts. However, it could belong to another instance, right? To avoid this issue, it seems best only to remove the (own) socket when the server shuts down.

**Comment by lastzero** [comment]
Thank you very much! I'll move ahead and merge this.
